# Generated by Django 5.1.7 on 2026-09-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_yhub_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("recruiter_account_manager", "Recruiter Account Manager"),
                    ("recruiter_freelancer", "Recruiter Freelancer"),
                ],
                default="recruiter_freelancer",
                max_length=40,
            ),
        ),
    ]
