# Generated by Django 5.1.7 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_applied",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
