# Generated by Django 5.1.7 on 2026-10-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_is_temp_pw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="refresh_token",
            field=models.TextField(),
        ),
    ]
