# Generated by Django 5.1.7 on 2026-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_is_applied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("recruiter_account_manager", "Recruiter Account Manager"),
                    ("recruiter_freelancer", "Recruiter Freelancer"),
                    ("recruiter_company_employee", "Recruiter Company Employee"),
                    ("recruiter_company_manager", "Recruiter Company Manager"),
                ],
                default="recruiter_freelancer",
                max_length=40,
            ),
        ),
    ]
