# Generated by Django 5.1.7 on 2026-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_temp_pw",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if the user is using a temporary password and must change it on login.",
            ),
        ),
    ]
