# Generated by Django 5.1.7 on 2026-09-12 06:31

import django.db.models.deletion
import django.utils.timezone
import recruiting.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "marketplace",
            "0005_rename_marketplace_status_9f481a_idx_marketplace_status_6913c8_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "current_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "current_company",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "current_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "work_authorization_status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("open_to_relocation", models.BooleanField(default=False)),
                (
                    "base_compensation_expectation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected annual base compensation.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "compensation_currency",
                    models.CharField(default="USD", max_length=10),
                ),
                ("earliest_start_date", models.DateField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded resume document.",
                        null=True,
                        upload_to=recruiting.models.candidate_resume_path,
                    ),
                ),
                (
                    "resume_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="External or CDN resume link.",
                        max_length=500,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="General recruiter notes regarding this candidate.",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        help_text="Recruiter who owns and created this candidate profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate",
                "verbose_name_plural": "Candidates",
                "db_table": "recruiting_candidates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruiterJobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "why_fit",
                    models.TextField(
                        help_text="Recruiter's explanation of why they are a strong fit to recruit for this specific role."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the application was reviewed.",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason provided by the Account Manager if the application is rejected.",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="The job being applied for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_applications",
                        to="marketplace.job",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        help_text="The freelancer recruiter applying to work on this job.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account Manager or Admin who approved or rejected this application.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_recruiter_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruiter Job Application",
                "verbose_name_plural": "Recruiter Job Applications",
                "db_table": "recruiting_job_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of answers to job-specific screening questions with snapshot metadata.",
                    ),
                ),
                (
                    "recruiter_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes and pitch provided by the recruiter for this submission.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=30,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the candidate was submitted.",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        help_text="The candidate being submitted.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="recruiting.candidate",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="The approved job application granting permission for this submission.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_submissions",
                        to="recruiting.recruiterjobapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Submission",
                "verbose_name_plural": "Candidate Submissions",
                "db_table": "recruiting_candidate_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["recruiter", "email"], name="recruiting__recruit_ff9c9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["email"], name="recruiting__email_57f09d_idx"),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="recruiting__first_n_aee4cc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_compensation_expectation__gte", 0),
                    ("base_compensation_expectation__isnull", True),
                    _connector="OR",
                ),
                name="candidate_compensation_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="recruiterjobapplication",
            index=models.Index(
                fields=["status", "created_at"], name="recruiting__status_4bc025_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recruiterjobapplication",
            index=models.Index(
                fields=["recruiter", "status"], name="recruiting__recruit_e47614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recruiterjobapplication",
            index=models.Index(
                fields=["job", "status"], name="recruiting__job_id_bc9abf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recruiterjobapplication",
            constraint=models.UniqueConstraint(
                fields=("recruiter", "job"), name="unique_recruiter_job_application"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatesubmission",
            index=models.Index(
                fields=["application", "status"], name="recruiting__applica_9790e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatesubmission",
            index=models.Index(
                fields=["candidate", "status"], name="recruiting__candida_40ad19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatesubmission",
            index=models.Index(
                fields=["status", "submitted_at"], name="recruiting__status_5d76d9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatesubmission",
            constraint=models.UniqueConstraint(
                fields=("application", "candidate"),
                name="unique_candidate_submission_per_application",
            ),
        ),
    ]
