# Generated by Django 5.1.7 on 2026-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatesubmission",
            name="stage",
            field=models.CharField(
                blank=True,
                default="am_review",
                help_text="Current stage in the hiring pipeline.",
                max_length=100,
            ),
        ),
    ]
