# Generated by Django 5.1.7 on 2026-09-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiting", "0003_candidate_availability_candidate_compensation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatesubmission",
            name="decision_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Decision note or commentary from the account manager or client.",
            ),
        ),
        migrations.AddField(
            model_name="candidatesubmission",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reason for rejection provided by the reviewer / account manager.",
            ),
        ),
    ]
