# Generated by Django 5.1.7 on 2026-10-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiting", "0004_candidatesubmission_decision_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="current_compensation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Current compensation / salary.",
                max_length=150,
            ),
        ),
    ]
