# Generated by Django 5.1.7 on 2026-09-12 03:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("logo_url", models.URLField(blank=True, default="", max_length=500)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                (
                    "company_size",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "funding_stage",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "industry",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "headquarters",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("onboarding", "Onboarding"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                    ),
                ),
                (
                    "why_company",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of highlights/reasons to join (e.g. [{'title': '...', 'description': '...'}]).",
                    ),
                ),
                (
                    "leadership",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of key leaders (e.g. [{'name': '...', 'title': '...', 'linkedin_url': '...'}]).",
                    ),
                ),
                (
                    "account_manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account manager responsible for this company account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "marketplace_companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("hiring", "Hiring"),
                            ("paused", "Paused"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("location", models.CharField(db_index=True, max_length=255)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        db_index=True,
                        default="full_time",
                        max_length=50,
                    ),
                ),
                (
                    "work_model",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("onsite", "On-site"),
                        ],
                        db_index=True,
                        default="hybrid",
                        max_length=50,
                    ),
                ),
                (
                    "experience",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("open_roles", models.PositiveIntegerField(default=1)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "job_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Complete job description text.",
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum annual salary in base currency.",
                        max_digits=12,
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum annual salary in base currency.",
                        max_digits=12,
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=10)),
                (
                    "equity_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Minimum equity percentage (e.g., 0.150 for 0.15%).",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "equity_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Maximum equity percentage (e.g., 0.400 for 0.40%).",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "visa_sponsorship",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "benefits_and_perks",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="All company benefits and perks.",
                    ),
                ),
                (
                    "company_to_yuvro_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of first-year salary paid by the company to Yuvro (e.g. 20.00).",
                        max_digits=5,
                    ),
                ),
                (
                    "yuvro_commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage retained by Yuvro as commission (e.g. 5.00).",
                        max_digits=5,
                    ),
                ),
                (
                    "payout_terms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of milestone days in ascending order (e.g. [30, 60, 90]).",
                    ),
                ),
                (
                    "candidate_questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Job-specific candidate questions configured by Account Manager.",
                    ),
                ),
                (
                    "must_haves",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of hard qualification requirements.",
                    ),
                ),
                (
                    "signals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Evaluation signals: {'green': [...], 'red': [...]}.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company offering this role.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="marketplace.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "marketplace_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["status", "industry"], name="marketplace_status_3fd9c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["account_manager", "status"],
                name="marketplace_account_9af1c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["company", "status"], name="marketplace_company_c0df26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "work_model", "employment_type"],
                name="marketplace_status_50657a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["salary_min", "salary_max"],
                name="marketplace_salary__9fbc84_idx",
            ),
        ),
    ]
