# Generated by Django 5.1.7 on 2026-10-01 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0015_company_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary company manager account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_company_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CompanyUserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=False,
                        help_text="True if this user is the primary company manager/contact.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this manager or employee belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="marketplace.company",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company User Profile",
                "verbose_name_plural": "Company User Profiles",
                "db_table": "marketplace_company_user_profiles",
                "indexes": [
                    models.Index(
                        fields=["company", "is_primary_contact"],
                        name="marketplace_company_b72a43_idx",
                    )
                ],
            },
        ),
    ]
