# Generated by Django 5.1.7 on 2026-10-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0017_job_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="equity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Equity percentage (e.g., 0.100 for 0.10%).",
                max_digits=6,
                null=True,
            ),
        ),
    ]
