# Generated by Django 5.1.7 on 2026-09-12 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="overview",
            field=models.TextField(
                blank=True, default="", help_text="Company overview and description."
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="company",
            name="why_role",
            field=models.TextField(
                blank=True, default="", help_text="Why these roles matter."
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["slug"], name="marketplace_slug_dfc499_idx"),
        ),
    ]
