# Generated by Django 5.1.7 on 2026-09-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_job_recruiter_slots"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recruiter",
            new_name="marketplace_status_6913c8_idx",
            old_name="marketplace_status_9f481a_idx",
        ),
        migrations.RenameIndex(
            model_name="recruiter",
            new_name="marketplace_account_423357_idx",
            old_name="marketplace_account_28cd9a_idx",
        ),
        migrations.RenameIndex(
            model_name="recruiter",
            new_name="marketplace_slug_8f33b4_idx",
            old_name="marketplace_slug_7d3b91_idx",
        ),
        migrations.RenameIndex(
            model_name="recruiter",
            new_name="marketplace_email_781814_idx",
            old_name="marketplace_email_501a3e_idx",
        ),
    ]
