# Generated by Django 5.1.7 on 2026-09-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0005_rename_marketplace_status_9f481a_idx_marketplace_status_6913c8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="hiring_process",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Job-specific hiring process steps (e.g. ['Screening', 'Technical interview', 'Hiring manager', 'Offer']).",
            ),
        ),
    ]
