# Generated by Django 5.1.7 on 2026-09-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_job_target_companies"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="company",
            new_name="marketplace_industr_18d67f_idx",
            old_name="marketplace_industry_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="marketplace_account_749358_idx",
            old_name="marketplace_am_idx",
        ),
    ]
