# Generated by Django 5.1.7 on 2026-09-25

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0009_rename_marketplace_industry_idx_marketplace_industr_18d67f_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("linkedin", models.CharField(blank=True, default="", max_length=500)),
                ("experience_years", models.CharField(blank=True, default="", max_length=50)),
                (
                    "top_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top 3 roles or specializations (e.g. ['AI / ML', 'Founding Engineer', 'Backend Engineer']).",
                    ),
                ),
                (
                    "early_stage_startup_hiring",
                    models.BooleanField(
                        default=True,
                        help_text="Has experience recruiting for early-stage startups.",
                    ),
                ),
                (
                    "startup_hiring_detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Details of early-stage startup hiring achievements.",
                    ),
                ),
                (
                    "hiring_geography",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Geographies/countries where the recruiter hires (e.g. 'India, United States').",
                        max_length=255,
                    ),
                ),
                (
                    "sourcing_tools",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary sourcing tools (e.g. 'LinkedIn Recruiter, Gem, GitHub search').",
                        max_length=500,
                    ),
                ),
                (
                    "hiring_references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of reference links or contacts (e.g. ['linkedin.com/in/arjun-rao', 'linkedin.com/in/kavya-n']).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("decision_notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_recruiter_network_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="User account associated with this application.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruiter Application",
                "verbose_name_plural": "Recruiter Applications",
                "db_table": "marketplace_recruiter_applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="marketplace_status_936fa1_idx"),
                    models.Index(fields=["email"], name="marketplace_email_7b51b3_idx"),
                ],
            },
        ),
    ]
