# Generated by Django 5.1.7 on 2026-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_recruiterapplication"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recruiterapplication",
            new_name="marketplace_status_7dd1f7_idx",
            old_name="marketplace_status_936fa1_idx",
        ),
        migrations.RenameIndex(
            model_name="recruiterapplication",
            new_name="marketplace_email_1b9fb7_idx",
            old_name="marketplace_email_7b51b3_idx",
        ),
        migrations.AddField(
            model_name="recruiterapplication",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
