# Generated by Django 5.1.7 on 2026-10-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0018_job_equity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="equity_max",
        ),
        migrations.RemoveField(
            model_name="job",
            name="equity_min",
        ),
    ]
