# Generated by Django 5.1.7 on 2026-09-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiting", "0002_candidatesubmission_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="availability",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Availability / notice period string (e.g. 4 weeks notice, Immediate).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="compensation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text representation of compensation / salary expectation.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="github_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="candidate",
            name="notice_period",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Notice period if applicable.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="portfolio_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="recruiterjobapplication",
            name="why_fit",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Recruiter's explanation of why they are a strong fit to recruit for this specific role.",
            ),
        ),
    ]
