/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmRouteImport } from './routes/am'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CrossListRouteImport } from './routes/cross-list'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchmakerRouteImport } from './routes/matchmaker'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubmitCandidateRouteImport } from './routes/submit-candidate'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AmIndexRouteImport } from './routes/am.index'
import { Route as AmCalendarRouteImport } from './routes/am.calendar'
import { Route as AmLoginRouteImport } from './routes/am.login'
import { Route as AmMessagesRouteImport } from './routes/am.messages'
import { Route as AmNotificationsRouteImport } from './routes/am.notifications'
import { Route as AmPayoutsRouteImport } from './routes/am.payouts'
import { Route as AmReportsRouteImport } from './routes/am.reports'
import { Route as AmSettingsRouteImport } from './routes/am.settings'
import { Route as CandidatesActiveRouteImport } from './routes/candidates.active'
import { Route as CandidatesRejectedRouteImport } from './routes/candidates.rejected'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as CompanyAboutRouteImport } from './routes/company.about'
import { Route as CompanyBillingRouteImport } from './routes/company.billing'
import { Route as CompanyIntegrationsRouteImport } from './routes/company.integrations'
import { Route as CompanyLoginRouteImport } from './routes/company.login'
import { Route as CompanyNotificationsRouteImport } from './routes/company.notifications'
import { Route as CompanySettingsRouteImport } from './routes/company.settings'
import { Route as CompanySignupRouteImport } from './routes/company.signup'
import { Route as CompanyTeamRouteImport } from './routes/company.team'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AmCompaniesIndexRouteImport } from './routes/am.companies.index'
import { Route as AmCompaniesCompanyIdRouteImport } from './routes/am.companies.$companyId'
import { Route as AmCompaniesNewRouteImport } from './routes/am.companies.new'
import { Route as AmJobsIndexRouteImport } from './routes/am.jobs.index'
import { Route as AmJobsJobIdRouteImport } from './routes/am.jobs.$jobId'
import { Route as AmJobsApplicationsRouteImport } from './routes/am.jobs.applications'
import { Route as AmJobsNewRouteImport } from './routes/am.jobs.new'
import { Route as AmRecruitersIndexRouteImport } from './routes/am.recruiters.index'
import { Route as AmRecruitersRecruiterIdRouteImport } from './routes/am.recruiters.$recruiterId'
import { Route as AmRecruitersApplicationsRouteImport } from './routes/am.recruiters.applications'
import { Route as AmSubmissionsSubmissionIdRouteImport } from './routes/am.submissions.$submissionId'
import { Route as CompanyCandidatesSubmissionIdRouteImport } from './routes/company.candidates.$submissionId'
import { Route as CompanyCandidatesActiveRouteImport } from './routes/company.candidates.active'
import { Route as CompanyCandidatesOfferRouteImport } from './routes/company.candidates.offer'
import { Route as CompanyCandidatesRejectedRouteImport } from './routes/company.candidates.rejected'
import { Route as CompanyCandidatesReviewRouteImport } from './routes/company.candidates.review'
import { Route as CompanyJobsJobIdRouteImport } from './routes/company.jobs.$jobId'
import { Route as CompanyJobsNewRouteImport } from './routes/company.jobs.new'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs.$jobId.index'
import { Route as JobsJobIdFeedbackRouteImport } from './routes/jobs.$jobId.feedback'
import { Route as JobsJobIdMessagesRouteImport } from './routes/jobs.$jobId.messages'
import { Route as JobsJobIdPipelineRouteImport } from './routes/jobs.$jobId.pipeline'
import { Route as JobsJobIdSubmitRouteImport } from './routes/jobs.$jobId.submit'
import { Route as AmJobsJobIdEditRouteImport } from './routes/am.jobs.$jobId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmRoute = AmRouteImport.update({
  id: '/am',
  path: '/am',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossListRoute = CrossListRouteImport.update({
  id: '/cross-list',
  path: '/cross-list',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakerRoute = MatchmakerRouteImport.update({
  id: '/matchmaker',
  path: '/matchmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitCandidateRoute = SubmitCandidateRouteImport.update({
  id: '/submit-candidate',
  path: '/submit-candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AmIndexRoute = AmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AmRoute,
} as any)
const AmCalendarRoute = AmCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AmRoute,
} as any)
const AmLoginRoute = AmLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AmRoute,
} as any)
const AmMessagesRoute = AmMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AmRoute,
} as any)
const AmNotificationsRoute = AmNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AmRoute,
} as any)
const AmPayoutsRoute = AmPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AmRoute,
} as any)
const AmReportsRoute = AmReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AmRoute,
} as any)
const AmSettingsRoute = AmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AmRoute,
} as any)
const CandidatesActiveRoute = CandidatesActiveRouteImport.update({
  id: '/candidates/active',
  path: '/candidates/active',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRejectedRoute = CandidatesRejectedRouteImport.update({
  id: '/candidates/rejected',
  path: '/candidates/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAboutRoute = CompanyAboutRouteImport.update({
  id: '/company/about',
  path: '/company/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyBillingRoute = CompanyBillingRouteImport.update({
  id: '/company/billing',
  path: '/company/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIntegrationsRoute = CompanyIntegrationsRouteImport.update({
  id: '/company/integrations',
  path: '/company/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyLoginRoute = CompanyLoginRouteImport.update({
  id: '/company/login',
  path: '/company/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyNotificationsRoute = CompanyNotificationsRouteImport.update({
  id: '/company/notifications',
  path: '/company/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySettingsRoute = CompanySettingsRouteImport.update({
  id: '/company/settings',
  path: '/company/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySignupRoute = CompanySignupRouteImport.update({
  id: '/company/signup',
  path: '/company/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyTeamRoute = CompanyTeamRouteImport.update({
  id: '/company/team',
  path: '/company/team',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AmCompaniesIndexRoute = AmCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AmRoute,
} as any)
const AmCompaniesCompanyIdRoute = AmCompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => AmRoute,
} as any)
const AmCompaniesNewRoute = AmCompaniesNewRouteImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => AmRoute,
} as any)
const AmJobsIndexRoute = AmJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AmRoute,
} as any)
const AmJobsJobIdRoute = AmJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AmRoute,
} as any)
const AmJobsApplicationsRoute = AmJobsApplicationsRouteImport.update({
  id: '/jobs/applications',
  path: '/jobs/applications',
  getParentRoute: () => AmRoute,
} as any)
const AmJobsNewRoute = AmJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AmRoute,
} as any)
const AmRecruitersIndexRoute = AmRecruitersIndexRouteImport.update({
  id: '/recruiters/',
  path: '/recruiters/',
  getParentRoute: () => AmRoute,
} as any)
const AmRecruitersRecruiterIdRoute = AmRecruitersRecruiterIdRouteImport.update({
  id: '/recruiters/$recruiterId',
  path: '/recruiters/$recruiterId',
  getParentRoute: () => AmRoute,
} as any)
const AmRecruitersApplicationsRoute =
  AmRecruitersApplicationsRouteImport.update({
    id: '/recruiters/applications',
    path: '/recruiters/applications',
    getParentRoute: () => AmRoute,
  } as any)
const AmSubmissionsSubmissionIdRoute =
  AmSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AmRoute,
  } as any)
const CompanyCandidatesSubmissionIdRoute =
  CompanyCandidatesSubmissionIdRouteImport.update({
    id: '/company/candidates/$submissionId',
    path: '/company/candidates/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyCandidatesActiveRoute = CompanyCandidatesActiveRouteImport.update({
  id: '/company/candidates/active',
  path: '/company/candidates/active',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCandidatesOfferRoute = CompanyCandidatesOfferRouteImport.update({
  id: '/company/candidates/offer',
  path: '/company/candidates/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCandidatesRejectedRoute =
  CompanyCandidatesRejectedRouteImport.update({
    id: '/company/candidates/rejected',
    path: '/company/candidates/rejected',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanyCandidatesReviewRoute = CompanyCandidatesReviewRouteImport.update({
  id: '/company/candidates/review',
  path: '/company/candidates/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobsJobIdRoute = CompanyJobsJobIdRouteImport.update({
  id: '/company/jobs/$jobId',
  path: '/company/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobsNewRoute = CompanyJobsNewRouteImport.update({
  id: '/company/jobs/new',
  path: '/company/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const JobsJobIdFeedbackRoute = JobsJobIdFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const JobsJobIdMessagesRoute = JobsJobIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const JobsJobIdPipelineRoute = JobsJobIdPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const JobsJobIdSubmitRoute = JobsJobIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const AmJobsJobIdEditRoute = AmJobsJobIdEditRouteImport.update({
  id: '/jobs/$jobId_/edit',
  path: '/jobs/$jobId/edit',
  getParentRoute: () => AmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/am': typeof AmRouteWithChildren
  '/application': typeof ApplicationRoute
  '/calendar': typeof CalendarRoute
  '/cross-list': typeof CrossListRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/matchmaker': typeof MatchmakerRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/submit-candidate': typeof SubmitCandidateRoute
  '/verify-email': typeof VerifyEmailRoute
  '/am/calendar': typeof AmCalendarRoute
  '/am/login': typeof AmLoginRoute
  '/am/messages': typeof AmMessagesRoute
  '/am/notifications': typeof AmNotificationsRoute
  '/am/payouts': typeof AmPayoutsRoute
  '/am/reports': typeof AmReportsRoute
  '/am/settings': typeof AmSettingsRoute
  '/candidates/active': typeof CandidatesActiveRoute
  '/candidates/rejected': typeof CandidatesRejectedRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/billing': typeof CompanyBillingRoute
  '/company/integrations': typeof CompanyIntegrationsRoute
  '/company/login': typeof CompanyLoginRoute
  '/company/notifications': typeof CompanyNotificationsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/signup': typeof CompanySignupRoute
  '/company/team': typeof CompanyTeamRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/am/': typeof AmIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/am/companies/$companyId': typeof AmCompaniesCompanyIdRoute
  '/am/companies/new': typeof AmCompaniesNewRoute
  '/am/jobs/$jobId': typeof AmJobsJobIdRoute
  '/am/jobs/applications': typeof AmJobsApplicationsRoute
  '/am/jobs/new': typeof AmJobsNewRoute
  '/am/recruiters/$recruiterId': typeof AmRecruitersRecruiterIdRoute
  '/am/recruiters/applications': typeof AmRecruitersApplicationsRoute
  '/am/submissions/$submissionId': typeof AmSubmissionsSubmissionIdRoute
  '/company/candidates/$submissionId': typeof CompanyCandidatesSubmissionIdRoute
  '/company/candidates/active': typeof CompanyCandidatesActiveRoute
  '/company/candidates/offer': typeof CompanyCandidatesOfferRoute
  '/company/candidates/rejected': typeof CompanyCandidatesRejectedRoute
  '/company/candidates/review': typeof CompanyCandidatesReviewRoute
  '/company/jobs/$jobId': typeof CompanyJobsJobIdRoute
  '/company/jobs/new': typeof CompanyJobsNewRoute
  '/jobs/$jobId/feedback': typeof JobsJobIdFeedbackRoute
  '/jobs/$jobId/messages': typeof JobsJobIdMessagesRoute
  '/jobs/$jobId/pipeline': typeof JobsJobIdPipelineRoute
  '/jobs/$jobId/submit': typeof JobsJobIdSubmitRoute
  '/am/companies/': typeof AmCompaniesIndexRoute
  '/am/jobs/': typeof AmJobsIndexRoute
  '/am/recruiters/': typeof AmRecruitersIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/am/jobs/$jobId/edit': typeof AmJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/calendar': typeof CalendarRoute
  '/cross-list': typeof CrossListRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/matchmaker': typeof MatchmakerRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/submit-candidate': typeof SubmitCandidateRoute
  '/verify-email': typeof VerifyEmailRoute
  '/am/calendar': typeof AmCalendarRoute
  '/am/login': typeof AmLoginRoute
  '/am/messages': typeof AmMessagesRoute
  '/am/notifications': typeof AmNotificationsRoute
  '/am/payouts': typeof AmPayoutsRoute
  '/am/reports': typeof AmReportsRoute
  '/am/settings': typeof AmSettingsRoute
  '/candidates/active': typeof CandidatesActiveRoute
  '/candidates/rejected': typeof CandidatesRejectedRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/billing': typeof CompanyBillingRoute
  '/company/integrations': typeof CompanyIntegrationsRoute
  '/company/login': typeof CompanyLoginRoute
  '/company/notifications': typeof CompanyNotificationsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/signup': typeof CompanySignupRoute
  '/company/team': typeof CompanyTeamRoute
  '/am': typeof AmIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/company': typeof CompanyIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/am/companies/$companyId': typeof AmCompaniesCompanyIdRoute
  '/am/companies/new': typeof AmCompaniesNewRoute
  '/am/jobs/$jobId': typeof AmJobsJobIdRoute
  '/am/jobs/applications': typeof AmJobsApplicationsRoute
  '/am/jobs/new': typeof AmJobsNewRoute
  '/am/recruiters/$recruiterId': typeof AmRecruitersRecruiterIdRoute
  '/am/recruiters/applications': typeof AmRecruitersApplicationsRoute
  '/am/submissions/$submissionId': typeof AmSubmissionsSubmissionIdRoute
  '/company/candidates/$submissionId': typeof CompanyCandidatesSubmissionIdRoute
  '/company/candidates/active': typeof CompanyCandidatesActiveRoute
  '/company/candidates/offer': typeof CompanyCandidatesOfferRoute
  '/company/candidates/rejected': typeof CompanyCandidatesRejectedRoute
  '/company/candidates/review': typeof CompanyCandidatesReviewRoute
  '/company/jobs/$jobId': typeof CompanyJobsJobIdRoute
  '/company/jobs/new': typeof CompanyJobsNewRoute
  '/jobs/$jobId/feedback': typeof JobsJobIdFeedbackRoute
  '/jobs/$jobId/messages': typeof JobsJobIdMessagesRoute
  '/jobs/$jobId/pipeline': typeof JobsJobIdPipelineRoute
  '/jobs/$jobId/submit': typeof JobsJobIdSubmitRoute
  '/am/companies': typeof AmCompaniesIndexRoute
  '/am/jobs': typeof AmJobsIndexRoute
  '/am/recruiters': typeof AmRecruitersIndexRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
  '/am/jobs/$jobId/edit': typeof AmJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/am': typeof AmRouteWithChildren
  '/application': typeof ApplicationRoute
  '/calendar': typeof CalendarRoute
  '/cross-list': typeof CrossListRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/matchmaker': typeof MatchmakerRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/submit-candidate': typeof SubmitCandidateRoute
  '/verify-email': typeof VerifyEmailRoute
  '/am/calendar': typeof AmCalendarRoute
  '/am/login': typeof AmLoginRoute
  '/am/messages': typeof AmMessagesRoute
  '/am/notifications': typeof AmNotificationsRoute
  '/am/payouts': typeof AmPayoutsRoute
  '/am/reports': typeof AmReportsRoute
  '/am/settings': typeof AmSettingsRoute
  '/candidates/active': typeof CandidatesActiveRoute
  '/candidates/rejected': typeof CandidatesRejectedRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/billing': typeof CompanyBillingRoute
  '/company/integrations': typeof CompanyIntegrationsRoute
  '/company/login': typeof CompanyLoginRoute
  '/company/notifications': typeof CompanyNotificationsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/signup': typeof CompanySignupRoute
  '/company/team': typeof CompanyTeamRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/am/': typeof AmIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/am/companies/$companyId': typeof AmCompaniesCompanyIdRoute
  '/am/companies/new': typeof AmCompaniesNewRoute
  '/am/jobs/$jobId': typeof AmJobsJobIdRoute
  '/am/jobs/applications': typeof AmJobsApplicationsRoute
  '/am/jobs/new': typeof AmJobsNewRoute
  '/am/recruiters/$recruiterId': typeof AmRecruitersRecruiterIdRoute
  '/am/recruiters/applications': typeof AmRecruitersApplicationsRoute
  '/am/submissions/$submissionId': typeof AmSubmissionsSubmissionIdRoute
  '/company/candidates/$submissionId': typeof CompanyCandidatesSubmissionIdRoute
  '/company/candidates/active': typeof CompanyCandidatesActiveRoute
  '/company/candidates/offer': typeof CompanyCandidatesOfferRoute
  '/company/candidates/rejected': typeof CompanyCandidatesRejectedRoute
  '/company/candidates/review': typeof CompanyCandidatesReviewRoute
  '/company/jobs/$jobId': typeof CompanyJobsJobIdRoute
  '/company/jobs/new': typeof CompanyJobsNewRoute
  '/jobs/$jobId/feedback': typeof JobsJobIdFeedbackRoute
  '/jobs/$jobId/messages': typeof JobsJobIdMessagesRoute
  '/jobs/$jobId/pipeline': typeof JobsJobIdPipelineRoute
  '/jobs/$jobId/submit': typeof JobsJobIdSubmitRoute
  '/am/companies/': typeof AmCompaniesIndexRoute
  '/am/jobs/': typeof AmJobsIndexRoute
  '/am/recruiters/': typeof AmRecruitersIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/am/jobs/$jobId_/edit': typeof AmJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/am'
    | '/application'
    | '/calendar'
    | '/cross-list'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/matchmaker'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/pipeline'
    | '/profile'
    | '/referrals'
    | '/reset-password'
    | '/signup'
    | '/submit-candidate'
    | '/verify-email'
    | '/am/calendar'
    | '/am/login'
    | '/am/messages'
    | '/am/notifications'
    | '/am/payouts'
    | '/am/reports'
    | '/am/settings'
    | '/candidates/active'
    | '/candidates/rejected'
    | '/clients/$clientId'
    | '/company/about'
    | '/company/billing'
    | '/company/integrations'
    | '/company/login'
    | '/company/notifications'
    | '/company/settings'
    | '/company/signup'
    | '/company/team'
    | '/jobs/$jobId'
    | '/am/'
    | '/clients/'
    | '/company/'
    | '/jobs/'
    | '/am/companies/$companyId'
    | '/am/companies/new'
    | '/am/jobs/$jobId'
    | '/am/jobs/applications'
    | '/am/jobs/new'
    | '/am/recruiters/$recruiterId'
    | '/am/recruiters/applications'
    | '/am/submissions/$submissionId'
    | '/company/candidates/$submissionId'
    | '/company/candidates/active'
    | '/company/candidates/offer'
    | '/company/candidates/rejected'
    | '/company/candidates/review'
    | '/company/jobs/$jobId'
    | '/company/jobs/new'
    | '/jobs/$jobId/feedback'
    | '/jobs/$jobId/messages'
    | '/jobs/$jobId/pipeline'
    | '/jobs/$jobId/submit'
    | '/am/companies/'
    | '/am/jobs/'
    | '/am/recruiters/'
    | '/jobs/$jobId/'
    | '/am/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application'
    | '/calendar'
    | '/cross-list'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/matchmaker'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/pipeline'
    | '/profile'
    | '/referrals'
    | '/reset-password'
    | '/signup'
    | '/submit-candidate'
    | '/verify-email'
    | '/am/calendar'
    | '/am/login'
    | '/am/messages'
    | '/am/notifications'
    | '/am/payouts'
    | '/am/reports'
    | '/am/settings'
    | '/candidates/active'
    | '/candidates/rejected'
    | '/clients/$clientId'
    | '/company/about'
    | '/company/billing'
    | '/company/integrations'
    | '/company/login'
    | '/company/notifications'
    | '/company/settings'
    | '/company/signup'
    | '/company/team'
    | '/am'
    | '/clients'
    | '/company'
    | '/jobs'
    | '/am/companies/$companyId'
    | '/am/companies/new'
    | '/am/jobs/$jobId'
    | '/am/jobs/applications'
    | '/am/jobs/new'
    | '/am/recruiters/$recruiterId'
    | '/am/recruiters/applications'
    | '/am/submissions/$submissionId'
    | '/company/candidates/$submissionId'
    | '/company/candidates/active'
    | '/company/candidates/offer'
    | '/company/candidates/rejected'
    | '/company/candidates/review'
    | '/company/jobs/$jobId'
    | '/company/jobs/new'
    | '/jobs/$jobId/feedback'
    | '/jobs/$jobId/messages'
    | '/jobs/$jobId/pipeline'
    | '/jobs/$jobId/submit'
    | '/am/companies'
    | '/am/jobs'
    | '/am/recruiters'
    | '/jobs/$jobId'
    | '/am/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/am'
    | '/application'
    | '/calendar'
    | '/cross-list'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/matchmaker'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/pipeline'
    | '/profile'
    | '/referrals'
    | '/reset-password'
    | '/signup'
    | '/submit-candidate'
    | '/verify-email'
    | '/am/calendar'
    | '/am/login'
    | '/am/messages'
    | '/am/notifications'
    | '/am/payouts'
    | '/am/reports'
    | '/am/settings'
    | '/candidates/active'
    | '/candidates/rejected'
    | '/clients/$clientId'
    | '/company/about'
    | '/company/billing'
    | '/company/integrations'
    | '/company/login'
    | '/company/notifications'
    | '/company/settings'
    | '/company/signup'
    | '/company/team'
    | '/jobs/$jobId'
    | '/am/'
    | '/clients/'
    | '/company/'
    | '/jobs/'
    | '/am/companies/$companyId'
    | '/am/companies/new'
    | '/am/jobs/$jobId'
    | '/am/jobs/applications'
    | '/am/jobs/new'
    | '/am/recruiters/$recruiterId'
    | '/am/recruiters/applications'
    | '/am/submissions/$submissionId'
    | '/company/candidates/$submissionId'
    | '/company/candidates/active'
    | '/company/candidates/offer'
    | '/company/candidates/rejected'
    | '/company/candidates/review'
    | '/company/jobs/$jobId'
    | '/company/jobs/new'
    | '/jobs/$jobId/feedback'
    | '/jobs/$jobId/messages'
    | '/jobs/$jobId/pipeline'
    | '/jobs/$jobId/submit'
    | '/am/companies/'
    | '/am/jobs/'
    | '/am/recruiters/'
    | '/jobs/$jobId/'
    | '/am/jobs/$jobId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmRoute: typeof AmRouteWithChildren
  ApplicationRoute: typeof ApplicationRoute
  CalendarRoute: typeof CalendarRoute
  CrossListRoute: typeof CrossListRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MatchmakerRoute: typeof MatchmakerRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PipelineRoute: typeof PipelineRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SubmitCandidateRoute: typeof SubmitCandidateRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CandidatesActiveRoute: typeof CandidatesActiveRoute
  CandidatesRejectedRoute: typeof CandidatesRejectedRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  CompanyAboutRoute: typeof CompanyAboutRoute
  CompanyBillingRoute: typeof CompanyBillingRoute
  CompanyIntegrationsRoute: typeof CompanyIntegrationsRoute
  CompanyLoginRoute: typeof CompanyLoginRoute
  CompanyNotificationsRoute: typeof CompanyNotificationsRoute
  CompanySettingsRoute: typeof CompanySettingsRoute
  CompanySignupRoute: typeof CompanySignupRoute
  CompanyTeamRoute: typeof CompanyTeamRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  ClientsIndexRoute: typeof ClientsIndexRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  CompanyCandidatesSubmissionIdRoute: typeof CompanyCandidatesSubmissionIdRoute
  CompanyCandidatesActiveRoute: typeof CompanyCandidatesActiveRoute
  CompanyCandidatesOfferRoute: typeof CompanyCandidatesOfferRoute
  CompanyCandidatesRejectedRoute: typeof CompanyCandidatesRejectedRoute
  CompanyCandidatesReviewRoute: typeof CompanyCandidatesReviewRoute
  CompanyJobsJobIdRoute: typeof CompanyJobsJobIdRoute
  CompanyJobsNewRoute: typeof CompanyJobsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/am': {
      id: '/am'
      path: '/am'
      fullPath: '/am'
      preLoaderRoute: typeof AmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-list': {
      id: '/cross-list'
      path: '/cross-list'
      fullPath: '/cross-list'
      preLoaderRoute: typeof CrossListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaker': {
      id: '/matchmaker'
      path: '/matchmaker'
      fullPath: '/matchmaker'
      preLoaderRoute: typeof MatchmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-candidate': {
      id: '/submit-candidate'
      path: '/submit-candidate'
      fullPath: '/submit-candidate'
      preLoaderRoute: typeof SubmitCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/am/': {
      id: '/am/'
      path: '/'
      fullPath: '/am/'
      preLoaderRoute: typeof AmIndexRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/calendar': {
      id: '/am/calendar'
      path: '/calendar'
      fullPath: '/am/calendar'
      preLoaderRoute: typeof AmCalendarRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/login': {
      id: '/am/login'
      path: '/login'
      fullPath: '/am/login'
      preLoaderRoute: typeof AmLoginRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/messages': {
      id: '/am/messages'
      path: '/messages'
      fullPath: '/am/messages'
      preLoaderRoute: typeof AmMessagesRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/notifications': {
      id: '/am/notifications'
      path: '/notifications'
      fullPath: '/am/notifications'
      preLoaderRoute: typeof AmNotificationsRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/payouts': {
      id: '/am/payouts'
      path: '/payouts'
      fullPath: '/am/payouts'
      preLoaderRoute: typeof AmPayoutsRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/reports': {
      id: '/am/reports'
      path: '/reports'
      fullPath: '/am/reports'
      preLoaderRoute: typeof AmReportsRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/settings': {
      id: '/am/settings'
      path: '/settings'
      fullPath: '/am/settings'
      preLoaderRoute: typeof AmSettingsRouteImport
      parentRoute: typeof AmRoute
    }
    '/candidates/active': {
      id: '/candidates/active'
      path: '/candidates/active'
      fullPath: '/candidates/active'
      preLoaderRoute: typeof CandidatesActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/rejected': {
      id: '/candidates/rejected'
      path: '/candidates/rejected'
      fullPath: '/candidates/rejected'
      preLoaderRoute: typeof CandidatesRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/about': {
      id: '/company/about'
      path: '/company/about'
      fullPath: '/company/about'
      preLoaderRoute: typeof CompanyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/billing': {
      id: '/company/billing'
      path: '/company/billing'
      fullPath: '/company/billing'
      preLoaderRoute: typeof CompanyBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/integrations': {
      id: '/company/integrations'
      path: '/company/integrations'
      fullPath: '/company/integrations'
      preLoaderRoute: typeof CompanyIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/login': {
      id: '/company/login'
      path: '/company/login'
      fullPath: '/company/login'
      preLoaderRoute: typeof CompanyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/notifications': {
      id: '/company/notifications'
      path: '/company/notifications'
      fullPath: '/company/notifications'
      preLoaderRoute: typeof CompanyNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/settings': {
      id: '/company/settings'
      path: '/company/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/signup': {
      id: '/company/signup'
      path: '/company/signup'
      fullPath: '/company/signup'
      preLoaderRoute: typeof CompanySignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/team': {
      id: '/company/team'
      path: '/company/team'
      fullPath: '/company/team'
      preLoaderRoute: typeof CompanyTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/am/companies/': {
      id: '/am/companies/'
      path: '/companies'
      fullPath: '/am/companies/'
      preLoaderRoute: typeof AmCompaniesIndexRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/companies/$companyId': {
      id: '/am/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/am/companies/$companyId'
      preLoaderRoute: typeof AmCompaniesCompanyIdRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/companies/new': {
      id: '/am/companies/new'
      path: '/companies/new'
      fullPath: '/am/companies/new'
      preLoaderRoute: typeof AmCompaniesNewRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/jobs/': {
      id: '/am/jobs/'
      path: '/jobs'
      fullPath: '/am/jobs/'
      preLoaderRoute: typeof AmJobsIndexRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/jobs/$jobId': {
      id: '/am/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/am/jobs/$jobId'
      preLoaderRoute: typeof AmJobsJobIdRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/jobs/applications': {
      id: '/am/jobs/applications'
      path: '/jobs/applications'
      fullPath: '/am/jobs/applications'
      preLoaderRoute: typeof AmJobsApplicationsRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/jobs/new': {
      id: '/am/jobs/new'
      path: '/jobs/new'
      fullPath: '/am/jobs/new'
      preLoaderRoute: typeof AmJobsNewRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/recruiters/': {
      id: '/am/recruiters/'
      path: '/recruiters'
      fullPath: '/am/recruiters/'
      preLoaderRoute: typeof AmRecruitersIndexRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/recruiters/$recruiterId': {
      id: '/am/recruiters/$recruiterId'
      path: '/recruiters/$recruiterId'
      fullPath: '/am/recruiters/$recruiterId'
      preLoaderRoute: typeof AmRecruitersRecruiterIdRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/recruiters/applications': {
      id: '/am/recruiters/applications'
      path: '/recruiters/applications'
      fullPath: '/am/recruiters/applications'
      preLoaderRoute: typeof AmRecruitersApplicationsRouteImport
      parentRoute: typeof AmRoute
    }
    '/am/submissions/$submissionId': {
      id: '/am/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/am/submissions/$submissionId'
      preLoaderRoute: typeof AmSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AmRoute
    }
    '/company/candidates/$submissionId': {
      id: '/company/candidates/$submissionId'
      path: '/company/candidates/$submissionId'
      fullPath: '/company/candidates/$submissionId'
      preLoaderRoute: typeof CompanyCandidatesSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates/active': {
      id: '/company/candidates/active'
      path: '/company/candidates/active'
      fullPath: '/company/candidates/active'
      preLoaderRoute: typeof CompanyCandidatesActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates/offer': {
      id: '/company/candidates/offer'
      path: '/company/candidates/offer'
      fullPath: '/company/candidates/offer'
      preLoaderRoute: typeof CompanyCandidatesOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates/rejected': {
      id: '/company/candidates/rejected'
      path: '/company/candidates/rejected'
      fullPath: '/company/candidates/rejected'
      preLoaderRoute: typeof CompanyCandidatesRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates/review': {
      id: '/company/candidates/review'
      path: '/company/candidates/review'
      fullPath: '/company/candidates/review'
      preLoaderRoute: typeof CompanyCandidatesReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/jobs/$jobId': {
      id: '/company/jobs/$jobId'
      path: '/company/jobs/$jobId'
      fullPath: '/company/jobs/$jobId'
      preLoaderRoute: typeof CompanyJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/jobs/new': {
      id: '/company/jobs/new'
      path: '/company/jobs/new'
      fullPath: '/company/jobs/new'
      preLoaderRoute: typeof CompanyJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/jobs/$jobId/feedback': {
      id: '/jobs/$jobId/feedback'
      path: '/feedback'
      fullPath: '/jobs/$jobId/feedback'
      preLoaderRoute: typeof JobsJobIdFeedbackRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/jobs/$jobId/messages': {
      id: '/jobs/$jobId/messages'
      path: '/messages'
      fullPath: '/jobs/$jobId/messages'
      preLoaderRoute: typeof JobsJobIdMessagesRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/jobs/$jobId/pipeline': {
      id: '/jobs/$jobId/pipeline'
      path: '/pipeline'
      fullPath: '/jobs/$jobId/pipeline'
      preLoaderRoute: typeof JobsJobIdPipelineRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/jobs/$jobId/submit': {
      id: '/jobs/$jobId/submit'
      path: '/submit'
      fullPath: '/jobs/$jobId/submit'
      preLoaderRoute: typeof JobsJobIdSubmitRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/am/jobs/$jobId_/edit': {
      id: '/am/jobs/$jobId_/edit'
      path: '/jobs/$jobId/edit'
      fullPath: '/am/jobs/$jobId/edit'
      preLoaderRoute: typeof AmJobsJobIdEditRouteImport
      parentRoute: typeof AmRoute
    }
  }
}

interface AmRouteChildren {
  AmCalendarRoute: typeof AmCalendarRoute
  AmLoginRoute: typeof AmLoginRoute
  AmMessagesRoute: typeof AmMessagesRoute
  AmNotificationsRoute: typeof AmNotificationsRoute
  AmPayoutsRoute: typeof AmPayoutsRoute
  AmReportsRoute: typeof AmReportsRoute
  AmSettingsRoute: typeof AmSettingsRoute
  AmIndexRoute: typeof AmIndexRoute
  AmCompaniesCompanyIdRoute: typeof AmCompaniesCompanyIdRoute
  AmCompaniesNewRoute: typeof AmCompaniesNewRoute
  AmJobsJobIdRoute: typeof AmJobsJobIdRoute
  AmJobsApplicationsRoute: typeof AmJobsApplicationsRoute
  AmJobsNewRoute: typeof AmJobsNewRoute
  AmRecruitersRecruiterIdRoute: typeof AmRecruitersRecruiterIdRoute
  AmRecruitersApplicationsRoute: typeof AmRecruitersApplicationsRoute
  AmSubmissionsSubmissionIdRoute: typeof AmSubmissionsSubmissionIdRoute
  AmCompaniesIndexRoute: typeof AmCompaniesIndexRoute
  AmJobsIndexRoute: typeof AmJobsIndexRoute
  AmRecruitersIndexRoute: typeof AmRecruitersIndexRoute
  AmJobsJobIdEditRoute: typeof AmJobsJobIdEditRoute
}

const AmRouteChildren: AmRouteChildren = {
  AmCalendarRoute: AmCalendarRoute,
  AmLoginRoute: AmLoginRoute,
  AmMessagesRoute: AmMessagesRoute,
  AmNotificationsRoute: AmNotificationsRoute,
  AmPayoutsRoute: AmPayoutsRoute,
  AmReportsRoute: AmReportsRoute,
  AmSettingsRoute: AmSettingsRoute,
  AmIndexRoute: AmIndexRoute,
  AmCompaniesCompanyIdRoute: AmCompaniesCompanyIdRoute,
  AmCompaniesNewRoute: AmCompaniesNewRoute,
  AmJobsJobIdRoute: AmJobsJobIdRoute,
  AmJobsApplicationsRoute: AmJobsApplicationsRoute,
  AmJobsNewRoute: AmJobsNewRoute,
  AmRecruitersRecruiterIdRoute: AmRecruitersRecruiterIdRoute,
  AmRecruitersApplicationsRoute: AmRecruitersApplicationsRoute,
  AmSubmissionsSubmissionIdRoute: AmSubmissionsSubmissionIdRoute,
  AmCompaniesIndexRoute: AmCompaniesIndexRoute,
  AmJobsIndexRoute: AmJobsIndexRoute,
  AmRecruitersIndexRoute: AmRecruitersIndexRoute,
  AmJobsJobIdEditRoute: AmJobsJobIdEditRoute,
}

const AmRouteWithChildren = AmRoute._addFileChildren(AmRouteChildren)

interface JobsJobIdRouteChildren {
  JobsJobIdFeedbackRoute: typeof JobsJobIdFeedbackRoute
  JobsJobIdMessagesRoute: typeof JobsJobIdMessagesRoute
  JobsJobIdPipelineRoute: typeof JobsJobIdPipelineRoute
  JobsJobIdSubmitRoute: typeof JobsJobIdSubmitRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdFeedbackRoute: JobsJobIdFeedbackRoute,
  JobsJobIdMessagesRoute: JobsJobIdMessagesRoute,
  JobsJobIdPipelineRoute: JobsJobIdPipelineRoute,
  JobsJobIdSubmitRoute: JobsJobIdSubmitRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmRoute: AmRouteWithChildren,
  ApplicationRoute: ApplicationRoute,
  CalendarRoute: CalendarRoute,
  CrossListRoute: CrossListRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MatchmakerRoute: MatchmakerRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PipelineRoute: PipelineRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SubmitCandidateRoute: SubmitCandidateRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CandidatesActiveRoute: CandidatesActiveRoute,
  CandidatesRejectedRoute: CandidatesRejectedRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  CompanyAboutRoute: CompanyAboutRoute,
  CompanyBillingRoute: CompanyBillingRoute,
  CompanyIntegrationsRoute: CompanyIntegrationsRoute,
  CompanyLoginRoute: CompanyLoginRoute,
  CompanyNotificationsRoute: CompanyNotificationsRoute,
  CompanySettingsRoute: CompanySettingsRoute,
  CompanySignupRoute: CompanySignupRoute,
  CompanyTeamRoute: CompanyTeamRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  ClientsIndexRoute: ClientsIndexRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  CompanyCandidatesSubmissionIdRoute: CompanyCandidatesSubmissionIdRoute,
  CompanyCandidatesActiveRoute: CompanyCandidatesActiveRoute,
  CompanyCandidatesOfferRoute: CompanyCandidatesOfferRoute,
  CompanyCandidatesRejectedRoute: CompanyCandidatesRejectedRoute,
  CompanyCandidatesReviewRoute: CompanyCandidatesReviewRoute,
  CompanyJobsJobIdRoute: CompanyJobsJobIdRoute,
  CompanyJobsNewRoute: CompanyJobsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
