# Generated by Django 5.1.7 on 2026-09-27

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Recruiters", "Recruiters"),
                            ("Submissions", "Submissions"),
                            ("Jobs", "Jobs"),
                            ("Pipeline", "Pipeline"),
                            ("Company", "Company"),
                            ("General", "General"),
                        ],
                        db_index=True,
                        default="General",
                        max_length=50,
                    ),
                ),
                ("notification_type", models.CharField(db_index=True, max_length=100)),
                ("link", models.CharField(blank=True, default="", max_length=500)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read", models.BooleanField(db_index=True, default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who receives this notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "core_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read", "-created_at"],
                        name="core_notif_recip_read_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="core_notif_recip_date_idx",
                    ),
                    models.Index(
                        fields=["category", "created_at"],
                        name="core_notif_cat_date_idx",
                    ),
                ],
            },
        ),
    ]
