# Generated by Django 5.1.7 on 2026-09-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="core_notifi_recipie_0a2052_idx",
            old_name="core_notif_recip_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="core_notifi_recipie_af5bd4_idx",
            old_name="core_notif_recip_date_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="core_notifi_categor_6be574_idx",
            old_name="core_notif_cat_date_idx",
        ),
    ]
